# fly.toml app configuration file generated for roadtown on 2023-07-26T00:04:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "roadtown"
primary_region = "bos"
console_command = "/code/manage.py shell"

[env]
  PORT = "8000"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[mounts]
  source = "roadtown_data"
  destination = "/data"
