# Generated by Django 5.1.1 on 2025-06-13 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("turkeytrot", "0001_initial"),
        ("wagtaildocs", "0014_alter_document_file_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turkeytrotpage",
            name="sponsor_pdf_url",
        ),
        migrations.AddField(
            model_name="turkeytrotpage",
            name="sponsor_packet_pdf",
            field=models.ForeignKey(
                blank=True,
                help_text="Upload sponsor packet PDF",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtaildocs.document",
            ),
        ),
    ]
